// Set up Kinect stuff
var ips = ["192.168.1.2", "192.168.1.3", "192.168.1.5", "192.168.1.4"];
//var ips = ["192.168.1.5", 192.168.1.3", "192.168.1.2"];
var JOINT = "SPINEBASE";
var SEL_JOINTS = [
  "HEAD", "HANDRIGHT", "HANDLEFT", "ELBOWRIGHT", "ELBOWLEFT", "SHOULDERRIGHT", "SHOULDERLEFT", "SPINEMID", "SPINEBASE", "KNEELEFT", "KNEERIGHT", "FOOTLEFT", "FOOTRIGHT"];

// SHUSHING
var SH_JOINT = "HEAD";
var SHUSH_TH = 0.001;
var SHUSH_VOL_MIN = -1;

// STRIKING
var STR_JOINT = "HANDRIGHT"
var STR_TH = 0.4;
var STR_WAIT_TH = 60;

// DEATH
var DEATH_TH = 100;

// PLAYING SOUNDS
var LOOP_WAIT_TH = 60;

// SIZE
var w = 40;
var h = 36;

var IS_ALL_QUAD_STRIKE = true;

// Joint names directory
var JOINT_NAMES = [
  "SPINEBASE",
  "SPINEMID",
  "NECK",
  "HEAD",
  "SHOULDERLEFT",
  "ELBOWLEFT",
  "WRISTLEFT",
  "HANDLEFT",
  "SHOULDERRIGHT",
  "ELBOWRIGHT",
  "WRISTRIGHT",
  "HANDRIGHT",
  "HIPLEFT",
  "KNEELEFT",
  "ANKLELEFT",
  "FOOTLEFT",
  "HIPRIGHT",
  "KNEERIGHT",
  "ANKLERIGHT",
  "FOOTRIGHT",
  "SPINESHOULDER",
  "HANDTIPLEFT ",
  "THUMBLEFT",
  "HANDTIPRIGHT",
  "THUMBRIGHT",
  ]